### ISSUE TITLE
Unable use udevil/devmon to mount exfat devices without modification

### ISSUE THREAD

**Issue by sensslen** [mati75/udevil#4]
When using devmon to mount external drives when plugged in, I noticed that I was unable to get exfat drives to mount with stock options. However I was able to patch the udevil configuration file using the resolution described [here](https://bbs.archlinux.org/viewtopic.php?id=257699). Might this be a bullseye issue?

Environment:
OS: [raspberry pi os](https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-01-28/)
Hardware: Raspberry Pi Compute Module v3 / Raspberry Pi 3B plus
udisks2 is not installed

**Comment by mati75** [comment]
If this is Debian bug, it should be reported there. However it's already reported upstream:

https://github.com/IgnorantGuru/udevil/issues/89

**Comment by sensslen** [comment]
Just out of interrest, Isn't this the source of the official debian version of udevil?

**Comment by mati75** [comment]
It is, but bugs should be reported here: https://bugs.debian.org/cgi-bin/pkgreport.cgi?repeatmerged=no&src=udevil 

For this specific one already exist: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968924
